FROM spark:4.1.2-python3

USER root

WORKDIR /app

RUN curl -fL https://repo1.maven.org/maven2/org/apache/hadoop/hadoop-aws/3.4.2/hadoop-aws-3.4.2.jar -o /opt/spark/jars/hadoop-aws-3.4.2.jar

COPY src ./src

USER spark


